### ISSUE TITLE
Create demo flow to show all functionality in clean way for install at site

### ISSUE THREAD

**Issue by clowrey** [keptan/node-red-contrib-led-matrix#15]
I want this to be as professional looking as possible, while still showing off things like gif icons - so you could have weather based icons that could take the weather data from online nodes - or use the local sensor data and show the color changing based on temperature etc.

**Comment by keptan** [comment]
changed the text to change colour based on the temperature and humidity

**Comment by keptan** [comment]
looked at some weather nodes, both require API keys that aren't free anymore
Was hoping to play a rain gif when it was raining etc

**Comment by clowrey** [comment]
Okay - make a demo flow using the BME temp to change an image from a snowflake to a fire if its warm. Maybe some image for good temperatures too
