### ISSUE TITLE
Change RGB Sequence

### ISSUE THREAD

**Issue by cheesykyle** [keptan/node-red-contrib-led-matrix#25]
When using the base library from hzeller, my panels require the `--led-rgb-sequence` flag set as RBG instead of the default RGB. 

How would I implement this transform? Ideally it'd be great to have a configurable option in the led-matrix configuration node.

**Comment by keptan** [comment]
looking into this

**Comment by keptan** [comment]
https://github.com/easybotics/node-red-contrib-easybotics-led-matrix/pull/28
https://github.com/easybotics/node-rpi-rgb-led-matrix/commit/6d4b0b73ca482bbcb0a214d0f0391b2a76808c94

Added a RGB SEQUENCE option, it's similiar to the hardware mapping option in that you'll have to restart node-red for it to apply.

![example](https://u.teknik.io/iGJyl.png)

It's up on NPM https://www.npmjs.com/package/node-red-contrib-easybotics-led-matrix
