### ISSUE TITLE
Remapping Matrix

### ISSUE THREAD

**Issue by CCSnell** [keptan/node-red-contrib-led-matrix#30]
How can I use the led-pixel-mapper along with this node? I am trying to remap 4 chained pixels in a U-Shape. I have tried several combinations of settings attempting to get this working to no avail. The panels are 64x32 four chained into a U from a Adafruit Matrix+RTC.

>->
^-<-HAT

Any advice would be appreciated.

**Comment by keptan** [comment]
looking into this

**Comment by clowrey** [comment]
This should now work with the custom parameters you can set.
