### ISSUE TITLE
How do Iset these settings?

### ISSUE THREAD

**Issue by marksmanaz** [keptan/node-red-contrib-led-matrix#31]
Hello, I am getting terrible ghosting with my 4 64x64 panels. I can correct them when using these parameters with the demo apps but I have no idea how to set these in the control node or else where. Any help is appreciated, thank you.

--led-pwm-bits=11 --led-scan-mode=0  --led-slowdown-gpio=2 --led-pwm-lsb-nanoseconds=110

**Comment by keptan** [comment]
Hello, it's possible to add all these as parameters, it's just a balance of how much we clutter up the settings page

will probably add a drop down for advanced settings, or an input box where you can enter them as flags

**Comment by keptan** [comment]
https://github.com/easybotics/node-rpi-rgb-led-matrix/commit/089e77651b6783d90289d2bd0bce80dc0fd82d05

backend done for this, waiting on frontend

**Comment by keptan** [comment]
https://github.com/easybotics/node-red-contrib-easybotics-led-matrix/commit/e2f714c79f573dbc2990645d99ad9c7524610376

frontend is done thanks to @ryanmich251 and it'll be published on npm soon
here is an example of me overriding the RGB sequence with the cli args
![](https://u.teknik.io/lhi13.png)

arguments are separated with spaces just as in the command line
runtime arguments like dropping privilege after running or daemonizing aren't supported
