### ISSUE TITLE
Controlling brightness using Dashboard slider

### ISSUE THREAD

**Issue by devjulie** [keptan/node-red-contrib-led-matrix#36]
Hi,
Thanks for the great node. Ive been making a simple time/date/weather display and trying to make it editable from Dashboard. I'm fairly new to Node Red so I might be missing something but I'm really struggling to link brightness of the LED matrix to a simple Dashboard slider. Everything I've read seems to say configuration node values can't be edited at runtime and the brightness value is in the configuration node. Any help you can offer is greatly appreciated.
Thanks

**Comment by ryanmich251** [comment]
I'm guessing this probably isn't an issue anymore, but this isn't possible with the way the project is currently written, the brightness values pretty much only get updated when node-red is restarted. Additionally, if that is the case that the node red dashboard can't modify configuration nodes (I'm not familiar with the dashboard), then this would probably require us to add a new node to update the brightness.

Closing this issue for now, if this issue still affects anyone, feel free to reopen it.
